### ISSUE TITLE
Seaside WAFileLibrary generates exception on use of addAllFilesIn: selector

### ISSUE THREAD

**Issue by mbratch** [gnu-smalltalk/smalltalk#15]
In Smalltalk 3.2.5...
When attempting to subclass `WAFileLibrary` and using the `addAllFilesIn:` selector, the following exception occurs:

    Object: File new "<-0x4cfa5080>" error: did not understand #first

The problem is in `Seaside.WAGNUSmalltalkPlatform>>filesIn:` in the file `smalltalk/packages/seaside/core/Seaside-GST.st`. An attempt is made to use the selector `first` on an object of class `File`:

    filesIn: aPathString [
        "Return a collection of absolute paths for all the files (no directories)
         in the directory given by aPathString must not include file names that start with ."
        | directory |
        directory := File name: aPathString.
        ^(directory files
            reject: [ :each | each first = $. ])   "ERROR here"
            collect: [ :each | each asString ]
    ]

**Comment by zecke** [comment]
I think you

```smalltalk
reject: [:each | each stripPath first = $. ]
```


each asString will give you an absolute path but the $. is in the name.

**Comment by mbratch** [comment]
Yes, that would be more correct. Thank you for the correction.

**Comment by zecke** [comment]
Sent a patch to the mailinglist and will merge it next weekend
